<?php

return [

    "service" => [
        ["icon" => "refrigerator", "name" => "холодильник"],
        ["icon" => "hairdryer", "name" => "фен"],
        ["icon" => "security-system", "name" => "систем1а безопасности"],
        ["icon" => "air-conditioner", "name" => "кондиционер"],
        ["icon" => "kitchen-stove", "name" => "плита для приготовления пищи"],
        ["icon" => "cosmetics", "name" => "туалетные средства"],
        ["icon" => "towel", "name" => "банные полотенца"],
        ["icon" => "cosmetics", "name" => "косметические средства"],
        ["icon" => "sink", "name" => "раковина"],
        ["icon" => "toilet", "name" => "унитаз"],
        ["icon" => "shower", "name" => "душевая кабина"],
        ["icon" => "slippers", "name" => "тапочки"],
        ["icon" => "no-icon", "name" => "вид на горы"],
        ["icon" => "wifi", "name" => "wi-fi"],
        ["icon" => "double", "name" => "двуспальная кровать"],
        ["icon" => "no-icon", "name" => "диван-кровать"],
        ["icon" => "mirror", "name" => "зеркало"],
        ["icon" => "table", "name" => "обеденный стол"],
        ["icon" => "no-icon", "name" => "раскладной диван"],
        ["icon" => "no-icon", "name" => "стул"],
        ["icon" => "cupboard", "name" => "мебельный гарнитур"],
        ["icon" => "no-icon", "name" => "стол"],
        ["icon" => "hanger", "name" => "вешалки"],
        ["icon" => "bedside-table", "name" => "комод"],
        ["icon" => "no-icon", "name" => "кофейный столик"],
        ["icon" => "dishes", "name" => "набор посуды"],
        ["icon" => "ironing-board", "name" => "гладильная доска"],
        ["icon" => "kitchen-stove", "name" => "кухня"],
        ["icon" => "no-icon", "name" => "номер для некурящих"],
        ["icon" => "no-icon", "name" => "столовые приборы"],
        ["icon" => "kettle", "name" => "чайник"],
        ["icon" => "safe", "name" => "сейф"],
        ["icon" => "no-icon", "name" => "кухонная посуда"],
        ["icon" => "tv", "name" => "кабельное телевидение"],
        ["icon" => "iron", "name" => "утюг"],
        ["icon" => "balcony", "name" => "балкон с красивым видом"],
        ["icon" => "microwave", "name" => "микроволновая печь"],
        ["icon" => "toilet", "name" => "санузел"],
        ["icon" => "twin", "name" => "две односпальные кровати"],
        ["icon" => "chair", "name" => "стулья"],
        ["icon" => "desk", "name" => "журнальный столик"],
        ["icon" => "cupboard", "name" => "шкаф для одежды"],
        ["icon" => "service", "name" => "обслуживание номеров"],
        ["icon" => "no-icon", "name" => "сушилка для белья"],
        ["icon" => "cupboard", "name" => "гардеробная"],
        ["icon" => "no-icon", "name" => "стаканы"],
        ["icon" => "no-icon", "name" => "туалетный столик"],
        ["icon" => "sauna", "name" => "банные принадлежности"],
        ["icon" => "private-room-entrance", "name" => "отдельный вход в номер"],
        ["icon" => "toilet", "name" => "биде"],
        ["icon" => "bathrobe", "name" => "халаты"],
        ["icon" => "no-icon", "name" => "телевизор с плоским экраном"],
        ["icon" => "cooler", "name" => "кулер на этаже"],
        ["icon" => "shower", "name" => "душ"],
        ["icon" => "view", "name" => "вид во двор"],
        ["icon" => "wifi", "name" => "интернет"],
        ["icon" => "tile", "name" => "плиточное покрытие"],
        ["icon" => "sofa", "name" => "гостиная зона"],
        ["icon" => "tea-set", "name" => "чайный набор"],
        ["icon" => "double", "name" => "кровать «king size»"],
        ["icon" => "no-icon", "name" => "мини-холодильник"],
        ["icon" => "bath-or-shower", "name" => "ванна или душевая кабина"],
        ["icon" => "no-icon", "name" => "мини-кухня"],
    ]

];
